/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.edu.uttt.vista;

import mx.edu.uttt.conexion.DaoArticulo;
import static mx.edu.uttt.conexion.DaoArticulo.printPersons;
import mx.edu.uttt.criteria.Criteria;
import mx.edu.uttt.concrete.AndCriteria;
import mx.edu.uttt.concrete.CriteriaFemale;
import mx.edu.uttt.concrete.CriteriaMale;
import mx.edu.uttt.concrete.CriteriaSingle;
import mx.edu.uttt.concrete.MarriedCriteria;
import mx.edu.uttt.concrete.OrCriteria;
import mx.edu.uttt.entidad.Person;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author net02
 */
public class FilterPattern extends javax.swing.JFrame {

    /**
     * Creates new form Filter
     */
    public FilterPattern() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnHombres = new javax.swing.JButton();
        btnMujeres = new javax.swing.JButton();
        btnSolteros = new javax.swing.JButton();
        btnSolteras = new javax.swing.JButton();
        btnCasados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("Selecciona el filtro que deseas aplicar:");

        btnHombres.setText("Hombres");
        btnHombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHombresActionPerformed(evt);
            }
        });

        btnMujeres.setText("Mujeres");
        btnMujeres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMujeresActionPerformed(evt);
            }
        });

        btnSolteros.setText("Hombres Solteros");
        btnSolteros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolterosActionPerformed(evt);
            }
        });

        btnSolteras.setText("Mujeres Solteras");
        btnSolteras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolterasActionPerformed(evt);
            }
        });

        btnCasados.setText("Casados");
        btnCasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasadosActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/edu/uttt/imagenes/df.png"))); // NOI18N

        jLabel3.setText("Equipo FilterPattern-DAII");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHombres, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMujeres, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCasados)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSolteros)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSolteras))
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHombres)
                    .addComponent(btnMujeres)
                    .addComponent(btnCasados)
                    .addComponent(btnSolteros)
                    .addComponent(btnSolteras))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHombresActionPerformed
        try {
            // TODO add your handling code here:
            List<Person> persons= new ArrayList<Person>();
            DaoArticulo nda = new DaoArticulo();
            persons=nda.buscarArticulos();

            Criteria single = new CriteriaSingle();
            Criteria female = new CriteriaFemale();
            Criteria male = new CriteriaMale();
            Criteria singleMale = new AndCriteria(single, male);
            Criteria singleOrFemale = new OrCriteria(single, female);
            Criteria married = new MarriedCriteria();
              
      
            System.out.println("Males: ");
            printPersons(male.meetCriteria(persons));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FilterPattern.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHombresActionPerformed

    private void btnMujeresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMujeresActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            List<Person> persons= new ArrayList<Person>();
            DaoArticulo nda = new DaoArticulo();
            persons=nda.buscarArticulos();

            
            Criteria single = new CriteriaSingle();
            Criteria female = new CriteriaFemale();
            Criteria male = new CriteriaMale();
            Criteria singleMale = new AndCriteria(single, male);
            Criteria singleOrFemale = new OrCriteria(single, female);
            Criteria married = new MarriedCriteria();
              

          System.out.println("\nFemales: ");
      printPersons(female.meetCriteria(persons));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FilterPattern.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMujeresActionPerformed

    private void btnSolterosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolterosActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            List<Person> persons= new ArrayList<Person>();
            DaoArticulo nda = new DaoArticulo();
            persons=nda.buscarArticulos();
 
            Criteria single = new CriteriaSingle();
            Criteria female = new CriteriaFemale();
            Criteria male = new CriteriaMale();
            Criteria singleMale = new AndCriteria(single, male);
            Criteria singleOrFemale = new OrCriteria(single, female);
            Criteria married = new MarriedCriteria();
              

         System.out.println("\nSingle Males: ");
      printPersons(singleMale.meetCriteria(persons));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FilterPattern.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSolterosActionPerformed

    private void btnSolterasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolterasActionPerformed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            List<Person> persons= new ArrayList<Person>();
            DaoArticulo nda = new DaoArticulo();
            persons=nda.buscarArticulos();

            Criteria single = new CriteriaSingle();
            Criteria female = new CriteriaFemale();
            Criteria male = new CriteriaMale();
            Criteria singleMale = new AndCriteria(single, male);
            Criteria singleOrFemale = new OrCriteria(single, female);
            Criteria married = new MarriedCriteria();
              

        System.out.println("\nSingle Or Females: ");
      printPersons(singleOrFemale.meetCriteria(persons));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FilterPattern.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSolterasActionPerformed

    private void btnCasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasadosActionPerformed
          
        try {
            List<Person> persons= new ArrayList<Person>();
            DaoArticulo nda = new DaoArticulo();
            persons=nda.buscarArticulos();
            
            
            Criteria single = new CriteriaSingle();
            Criteria female = new CriteriaFemale();
            Criteria male = new CriteriaMale();
            Criteria singleMale = new AndCriteria(single, male);
            Criteria singleOrFemale = new OrCriteria(single, female);
            Criteria married = new MarriedCriteria();
              
            System.out.println("Married: ");
            printPersons(married.meetCriteria(persons));
          
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FilterPattern.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCasadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilterPattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilterPattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilterPattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilterPattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilterPattern().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCasados;
    private javax.swing.JButton btnHombres;
    private javax.swing.JButton btnMujeres;
    private javax.swing.JButton btnSolteras;
    private javax.swing.JButton btnSolteros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
